//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_DialogueBox_H
#define METASPRITE_DialogueBox_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define DialogueBox_TILE_ORIGIN 0
#define DialogueBox_TILE_W 8
#define DialogueBox_TILE_H 8
#define DialogueBox_WIDTH 160
#define DialogueBox_HEIGHT 40
#define DialogueBox_TILE_COUNT 9
#define DialogueBox_PALETTE_COUNT 1
#define DialogueBox_COLORS_PER_PALETTE 4
#define DialogueBox_TOTAL_COLORS 4
#define DialogueBox_MAP_ATTRIBUTES 0

BANKREF_EXTERN(DialogueBox)

extern const palette_color_t DialogueBox_palettes[4];
extern const uint8_t DialogueBox_tiles[144];

extern const unsigned char DialogueBox_map[100];
#define DialogueBox_map_attributes DialogueBox_map

#endif
