# gbz80 specific Makefile

TOPDIR = ../../..

THIS = gbz80

ASSRC = __sdcc_call_hl.s abs.s mul.s div.s shift.s stubs.s crt0_rle.s \
	setjmp.s asm_string.s atomic_flag_test_and_set.s

include $(TOPDIR)/Makefile.common

AS = $(AS_GBZ80)

include ../Makefile.port


