# gbz80 specific Makefile

TOPDIR = ../../..

THIS = gbz80
ASSRC = __sdcc_call_hl.s mul.s div.s shift.s stubs.s crt0_rle.s setjmp.s asm_string.s

include $(TOPDIR)/Makefile.common

AS = $(AS_GBZ80)

include ../Makefile.port


