# NES specific Makefile

TOPDIR = ../../../..

THIS = nes
PORT = mos6502

CSRC = crlf.c

ASSRC =	crt0.s

CRT0 =	crt0.s

include $(TOPDIR)/Makefile.common

AS = $(AS_6500)

include ../../../Makefile.platform
