//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_apaimage_1_H
#define METASPRITE_apaimage_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define apaimage_1_TILE_ORIGIN 0
#define apaimage_1_TILE_W 8
#define apaimage_1_TILE_H 8
#define apaimage_1_WIDTH 160
#define apaimage_1_HEIGHT 144
#define apaimage_1_TILE_COUNT 360
#define apaimage_1_PALETTE_COUNT 1
#define apaimage_1_COLORS_PER_PALETTE 4
#define apaimage_1_TOTAL_COLORS 4

BANKREF_EXTERN(apaimage_1)

extern const palette_color_t apaimage_1_palettes[4];
extern const uint8_t apaimage_1_tiles[5760];


#endif
