//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_tileonly.bin -map -bin -tiles_only

#ifndef METASPRITE_binout_tileonly_H
#define METASPRITE_binout_tileonly_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_tileonly_TILE_ORIGIN 0
#define binout_tileonly_TILE_W 8
#define binout_tileonly_TILE_H 8
#define binout_tileonly_WIDTH 56
#define binout_tileonly_HEIGHT 96
#define binout_tileonly_TILES_WIDTH 7
#define binout_tileonly_TILES_HEIGHT 12
#define binout_tileonly_TILE_COUNT 45
#define binout_tileonly_PALETTE_COUNT 1
#define binout_tileonly_COLORS_PER_PALETTE 4
#define binout_tileonly_TOTAL_COLORS 4

BANKREF_EXTERN(binout_tileonly)

extern const palette_color_t binout_tileonly_palettes[4];
extern const uint8_t binout_tileonly_tiles[720];

#endif
