//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_maponly_sms.bin -map -bin -maps_only -pack_mode sms -bpp 4 -max_palettes 2 -use_map_attributes

#ifndef METASPRITE_binout_maponly_sms_H
#define METASPRITE_binout_maponly_sms_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_sms_TILE_ORIGIN 0
#define binout_maponly_sms_TILE_W 8
#define binout_maponly_sms_TILE_H 8
#define binout_maponly_sms_WIDTH 56
#define binout_maponly_sms_HEIGHT 96
#define binout_maponly_sms_TILES_WIDTH 7
#define binout_maponly_sms_TILES_HEIGHT 12
#define binout_maponly_sms_TILE_COUNT 45
#define binout_maponly_sms_PALETTE_COUNT 1
#define binout_maponly_sms_COLORS_PER_PALETTE 16
#define binout_maponly_sms_TOTAL_COLORS 16
#define binout_maponly_sms_MAP_ATTRIBUTES 0
#define binout_maponly_sms_MAP_ATTRIBUTES_WIDTH 7
#define binout_maponly_sms_MAP_ATTRIBUTES_HEIGHT 12
#define binout_maponly_sms_MAP_ATTRIBUTES_PACKED_WIDTH 7
#define binout_maponly_sms_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char binout_maponly_sms_map[168];
#define binout_maponly_sms_map_attributes binout_maponly_sms_map

BANKREF_EXTERN(binout_maponly_sms)

extern const palette_color_t binout_maponly_sms_palettes[16];

#endif
