//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_maponly_gbc.bin -map -bin -maps_only -pack_mode gb -bpp 2 -max_palettes 8 -use_map_attributes

#ifndef METASPRITE_binout_maponly_gbc_H
#define METASPRITE_binout_maponly_gbc_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_gbc_TILE_ORIGIN 0
#define binout_maponly_gbc_TILE_W 8
#define binout_maponly_gbc_TILE_H 8
#define binout_maponly_gbc_WIDTH 56
#define binout_maponly_gbc_HEIGHT 96
#define binout_maponly_gbc_TILE_COUNT 45
#define binout_maponly_gbc_PALETTE_COUNT 1
#define binout_maponly_gbc_COLORS_PER_PALETTE 4
#define binout_maponly_gbc_TOTAL_COLORS 4
#define binout_maponly_gbc_MAP_ATTRIBUTES binout_maponly_gbc_map_attributes
#define binout_maponly_gbc_MAP_ATTRIBUTES_WIDTH 7
#define binout_maponly_gbc_MAP_ATTRIBUTES_HEIGHT 12
#define binout_maponly_gbc_MAP_ATTRIBUTES_PACKED_WIDTH 7
#define binout_maponly_gbc_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char binout_maponly_gbc_map[84];
extern const unsigned char binout_maponly_gbc_map_attributes[84];

BANKREF_EXTERN(binout_maponly_gbc)

extern const palette_color_t binout_maponly_gbc_palettes[4];

#endif
