//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_maponly_gb.bin -map -bin -maps_only -pack_mode gb -bpp 2 -max_palettes 1 -noflip

#ifndef METASPRITE_binout_maponly_gb_H
#define METASPRITE_binout_maponly_gb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_gb_TILE_ORIGIN 0
#define binout_maponly_gb_TILE_W 8
#define binout_maponly_gb_TILE_H 8
#define binout_maponly_gb_WIDTH 56
#define binout_maponly_gb_HEIGHT 96
#define binout_maponly_gb_TILES_WIDTH 7
#define binout_maponly_gb_TILES_HEIGHT 12
#define binout_maponly_gb_TILE_COUNT 50
#define binout_maponly_gb_PALETTE_COUNT 1
#define binout_maponly_gb_COLORS_PER_PALETTE 4
#define binout_maponly_gb_TOTAL_COLORS 4
#define binout_maponly_gb_MAP_ATTRIBUTES 0
extern const unsigned char binout_maponly_gb_map[84];
#define binout_maponly_gb_map_attributes binout_maponly_gb_map

BANKREF_EXTERN(binout_maponly_gb)

extern const palette_color_t binout_maponly_gb_palettes[4];

#endif
