//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_maponly_nes.bin -map -bin -maps_only -pack_mode nes -bpp 2 -max_palettes 4 -use_nes_attributes -noflip

#ifndef METASPRITE_binout_maponly_nes_H
#define METASPRITE_binout_maponly_nes_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_nes_TILE_ORIGIN 0
#define binout_maponly_nes_TILE_W 8
#define binout_maponly_nes_TILE_H 8
#define binout_maponly_nes_WIDTH 56
#define binout_maponly_nes_HEIGHT 96
#define binout_maponly_nes_TILE_COUNT 50
#define binout_maponly_nes_PALETTE_COUNT 2
#define binout_maponly_nes_COLORS_PER_PALETTE 4
#define binout_maponly_nes_TOTAL_COLORS 8
#define binout_maponly_nes_MAP_ATTRIBUTES binout_maponly_nes_map_attributes
#define binout_maponly_nes_MAP_ATTRIBUTES_WIDTH 8
#define binout_maponly_nes_MAP_ATTRIBUTES_HEIGHT 32
#define binout_maponly_nes_MAP_ATTRIBUTES_PACKED_WIDTH 2
#define binout_maponly_nes_MAP_ATTRIBUTES_PACKED_HEIGHT 8
extern const unsigned char binout_maponly_nes_map[84];
extern const unsigned char binout_maponly_nes_map_attributes[16];

BANKREF_EXTERN(binout_maponly_nes)

extern const palette_color_t binout_maponly_nes_palettes[8];

#endif
