//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_maponly_gg.bin -map -bin -maps_only -pack_mode gg -bpp 4 -max_palettes 2 -use_map_attributes

#ifndef METASPRITE_binout_maponly_gg_H
#define METASPRITE_binout_maponly_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_gg_TILE_ORIGIN 0
#define binout_maponly_gg_TILE_W 8
#define binout_maponly_gg_TILE_H 8
#define binout_maponly_gg_WIDTH 56
#define binout_maponly_gg_HEIGHT 96
#define binout_maponly_gg_TILE_COUNT 45
#define binout_maponly_gg_PALETTE_COUNT 1
#define binout_maponly_gg_COLORS_PER_PALETTE 16
#define binout_maponly_gg_TOTAL_COLORS 16
#define binout_maponly_gg_MAP_ATTRIBUTES 0
#define binout_maponly_gg_MAP_ATTRIBUTES_WIDTH 7
#define binout_maponly_gg_MAP_ATTRIBUTES_HEIGHT 12
#define binout_maponly_gg_MAP_ATTRIBUTES_PACKED_WIDTH 7
#define binout_maponly_gg_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char binout_maponly_gg_map[168];
#define binout_maponly_gg_map_attributes binout_maponly_gg_map

BANKREF_EXTERN(binout_maponly_gg)

extern const palette_color_t binout_maponly_gg_palettes[16];

#endif
