//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gameboy.png -o /binout_basic.bin -map -bin

#ifndef METASPRITE_binout_basic_H
#define METASPRITE_binout_basic_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_basic_TILE_ORIGIN 0
#define binout_basic_TILE_W 8
#define binout_basic_TILE_H 8
#define binout_basic_WIDTH 56
#define binout_basic_HEIGHT 96
#define binout_basic_TILES_WIDTH 7
#define binout_basic_TILES_HEIGHT 12
#define binout_basic_TILE_COUNT 45
#define binout_basic_PALETTE_COUNT 1
#define binout_basic_COLORS_PER_PALETTE 4
#define binout_basic_TOTAL_COLORS 4
#define binout_basic_MAP_ATTRIBUTES 0
extern const unsigned char binout_basic_map[84];
#define binout_basic_map_attributes binout_basic_map

BANKREF_EXTERN(binout_basic)

extern const palette_color_t binout_basic_palettes[4];
extern const uint8_t binout_basic_tiles[720];

#endif
