//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_color_indexed_nums_map_4_H
#define METASPRITE_color_indexed_nums_map_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define color_indexed_nums_map_4_TILE_ORIGIN 0
#define color_indexed_nums_map_4_TILE_W 8
#define color_indexed_nums_map_4_TILE_H 8
#define color_indexed_nums_map_4_WIDTH 80
#define color_indexed_nums_map_4_HEIGHT 40
#define color_indexed_nums_map_4_TILE_COUNT 20
#define color_indexed_nums_map_4_PALETTE_COUNT 4
#define color_indexed_nums_map_4_COLORS_PER_PALETTE 4
#define color_indexed_nums_map_4_TOTAL_COLORS 16
#define color_indexed_nums_map_4_MAP_ATTRIBUTES color_indexed_nums_map_4_map_attributes
#define color_indexed_nums_map_4_MAP_ATTRIBUTES_WIDTH 10
#define color_indexed_nums_map_4_MAP_ATTRIBUTES_HEIGHT 5
#define color_indexed_nums_map_4_MAP_ATTRIBUTES_PACKED_WIDTH 10
#define color_indexed_nums_map_4_MAP_ATTRIBUTES_PACKED_HEIGHT 5
extern const unsigned char color_indexed_nums_map_4_map[50];
extern const unsigned char color_indexed_nums_map_4_map_attributes[50];

BANKREF_EXTERN(color_indexed_nums_map_4)

extern const uint8_t color_indexed_nums_map_4_tiles[320];

#endif
