//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_color_nums_map_2_H
#define METASPRITE_color_nums_map_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define color_nums_map_2_TILE_ORIGIN 0
#define color_nums_map_2_TILE_W 8
#define color_nums_map_2_TILE_H 8
#define color_nums_map_2_WIDTH 80
#define color_nums_map_2_HEIGHT 40
#define color_nums_map_2_TILE_COUNT 30
#define color_nums_map_2_PALETTE_COUNT 4
#define color_nums_map_2_COLORS_PER_PALETTE 4
#define color_nums_map_2_TOTAL_COLORS 16
#define color_nums_map_2_MAP_ATTRIBUTES color_nums_map_2_map_attributes
#define color_nums_map_2_MAP_ATTRIBUTES_WIDTH 10
#define color_nums_map_2_MAP_ATTRIBUTES_HEIGHT 5
#define color_nums_map_2_MAP_ATTRIBUTES_PACKED_WIDTH 10
#define color_nums_map_2_MAP_ATTRIBUTES_PACKED_HEIGHT 5
extern const unsigned char color_nums_map_2_map[50];
extern const unsigned char color_nums_map_2_map_attributes[50];

BANKREF_EXTERN(color_nums_map_2)

extern const palette_color_t color_nums_map_2_palettes[4];
extern const uint8_t color_nums_map_2_tiles[480];

#endif
