//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_color_nums_map_1_H
#define METASPRITE_color_nums_map_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define color_nums_map_1_TILE_ORIGIN 0
#define color_nums_map_1_TILE_W 8
#define color_nums_map_1_TILE_H 8
#define color_nums_map_1_WIDTH 80
#define color_nums_map_1_HEIGHT 40
#define color_nums_map_1_TILE_COUNT 40
#define color_nums_map_1_PALETTE_COUNT 4
#define color_nums_map_1_COLORS_PER_PALETTE 4
#define color_nums_map_1_TOTAL_COLORS 16
#define color_nums_map_1_MAP_ATTRIBUTES color_nums_map_1_map_attributes
#define color_nums_map_1_MAP_ATTRIBUTES_WIDTH 10
#define color_nums_map_1_MAP_ATTRIBUTES_HEIGHT 5
#define color_nums_map_1_MAP_ATTRIBUTES_PACKED_WIDTH 10
#define color_nums_map_1_MAP_ATTRIBUTES_PACKED_HEIGHT 5
extern const unsigned char color_nums_map_1_map[50];
extern const unsigned char color_nums_map_1_map_attributes[50];

BANKREF_EXTERN(color_nums_map_1)

extern const palette_color_t color_nums_map_1_palettes[16];
extern const uint8_t color_nums_map_1_tiles[640];

#endif
