//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_color_indexed_nums_map_8_H
#define METASPRITE_color_indexed_nums_map_8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define color_indexed_nums_map_8_TILE_ORIGIN 0
#define color_indexed_nums_map_8_TILE_W 8
#define color_indexed_nums_map_8_TILE_H 8
#define color_indexed_nums_map_8_WIDTH 80
#define color_indexed_nums_map_8_HEIGHT 40
#define color_indexed_nums_map_8_TILE_COUNT 30
#define color_indexed_nums_map_8_PALETTE_COUNT 4
#define color_indexed_nums_map_8_COLORS_PER_PALETTE 4
#define color_indexed_nums_map_8_TOTAL_COLORS 16
#define color_indexed_nums_map_8_MAP_ATTRIBUTES color_indexed_nums_map_8_map_attributes
#define color_indexed_nums_map_8_MAP_ATTRIBUTES_WIDTH 10
#define color_indexed_nums_map_8_MAP_ATTRIBUTES_HEIGHT 5
#define color_indexed_nums_map_8_MAP_ATTRIBUTES_PACKED_WIDTH 10
#define color_indexed_nums_map_8_MAP_ATTRIBUTES_PACKED_HEIGHT 5
extern const unsigned char color_indexed_nums_map_8_map[50];
extern const unsigned char color_indexed_nums_map_8_map_attributes[50];

BANKREF_EXTERN(color_indexed_nums_map_8)

extern const uint8_t color_indexed_nums_map_8_tiles[480];

#endif
