//AUTOGENERATED FILE FROM png2asset
// Conversion args: /GBDK_2020_logo.png -o /gbdklogo_1.c -map -bpp 2 -max_palettes 1 -pack_mode gb -noflip

#ifndef METASPRITE_gbdklogo_1_H
#define METASPRITE_gbdklogo_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdklogo_1_TILE_ORIGIN 0
#define gbdklogo_1_TILE_W 8
#define gbdklogo_1_TILE_H 8
#define gbdklogo_1_WIDTH 160
#define gbdklogo_1_HEIGHT 144
#define gbdklogo_1_TILES_WIDTH 20
#define gbdklogo_1_TILES_HEIGHT 18
#define gbdklogo_1_TILE_COUNT 39
#define gbdklogo_1_PALETTE_COUNT 1
#define gbdklogo_1_COLORS_PER_PALETTE 4
#define gbdklogo_1_TOTAL_COLORS 4
#define gbdklogo_1_MAP_ATTRIBUTES 0
extern const unsigned char gbdklogo_1_map[360];
#define gbdklogo_1_map_attributes gbdklogo_1_map

BANKREF_EXTERN(gbdklogo_1)

extern const palette_color_t gbdklogo_1_palettes[4];
extern const uint8_t gbdklogo_1_tiles[624];

#endif
