//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbdklogo_3_H
#define METASPRITE_gbdklogo_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdklogo_3_TILE_ORIGIN 0
#define gbdklogo_3_TILE_W 8
#define gbdklogo_3_TILE_H 8
#define gbdklogo_3_WIDTH 160
#define gbdklogo_3_HEIGHT 144
#define gbdklogo_3_TILE_COUNT 40
#define gbdklogo_3_PALETTE_COUNT 3
#define gbdklogo_3_COLORS_PER_PALETTE 4
#define gbdklogo_3_TOTAL_COLORS 12
#define gbdklogo_3_MAP_ATTRIBUTES gbdklogo_3_map_attributes
#define gbdklogo_3_MAP_ATTRIBUTES_WIDTH 20
#define gbdklogo_3_MAP_ATTRIBUTES_HEIGHT 32
#define gbdklogo_3_MAP_ATTRIBUTES_PACKED_WIDTH 5
#define gbdklogo_3_MAP_ATTRIBUTES_PACKED_HEIGHT 8

BANKREF_EXTERN(gbdklogo_3)

extern const palette_color_t gbdklogo_3_palettes[12];
extern const uint8_t gbdklogo_3_tiles[640];

extern const unsigned char gbdklogo_3_map[360];
extern const unsigned char gbdklogo_3_map_attributes[40];

#endif
