//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbdklogo_2_H
#define METASPRITE_gbdklogo_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdklogo_2_TILE_ORIGIN 0
#define gbdklogo_2_TILE_W 8
#define gbdklogo_2_TILE_H 8
#define gbdklogo_2_WIDTH 160
#define gbdklogo_2_HEIGHT 144
#define gbdklogo_2_TILE_COUNT 41
#define gbdklogo_2_PALETTE_COUNT 4
#define gbdklogo_2_COLORS_PER_PALETTE 4
#define gbdklogo_2_TOTAL_COLORS 16
#define gbdklogo_2_MAP_ATTRIBUTES gbdklogo_2_map_attributes
#define gbdklogo_2_MAP_ATTRIBUTES_WIDTH 20
#define gbdklogo_2_MAP_ATTRIBUTES_HEIGHT 18
#define gbdklogo_2_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define gbdklogo_2_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(gbdklogo_2)

extern const palette_color_t gbdklogo_2_palettes[16];
extern const uint8_t gbdklogo_2_tiles[656];

extern const unsigned char gbdklogo_2_map[360];
extern const unsigned char gbdklogo_2_map_attributes[360];

#endif
