//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hblankcopy_1_H
#define METASPRITE_hblankcopy_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hblankcopy_1_TILE_ORIGIN 0
#define hblankcopy_1_TILE_W 8
#define hblankcopy_1_TILE_H 8
#define hblankcopy_1_WIDTH 112
#define hblankcopy_1_HEIGHT 72
#define hblankcopy_1_TILE_COUNT 126
#define hblankcopy_1_PALETTE_COUNT 1
#define hblankcopy_1_COLORS_PER_PALETTE 4
#define hblankcopy_1_TOTAL_COLORS 4

BANKREF_EXTERN(hblankcopy_1)

extern const palette_color_t hblankcopy_1_palettes[4];
extern const uint8_t hblankcopy_1_tiles[2016];


#endif
