//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_largemap_6_H
#define METASPRITE_largemap_6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_6_TILE_ORIGIN 0
#define largemap_6_TILE_W 8
#define largemap_6_TILE_H 8
#define largemap_6_WIDTH 1248
#define largemap_6_HEIGHT 528
#define largemap_6_TILE_COUNT 217
#define largemap_6_PALETTE_COUNT 1
#define largemap_6_COLORS_PER_PALETTE 16
#define largemap_6_TOTAL_COLORS 16
#define largemap_6_MAP_ATTRIBUTES 0
#define largemap_6_MAP_ATTRIBUTES_WIDTH 156
#define largemap_6_MAP_ATTRIBUTES_HEIGHT 66
#define largemap_6_MAP_ATTRIBUTES_PACKED_WIDTH 156
#define largemap_6_MAP_ATTRIBUTES_PACKED_HEIGHT 66

BANKREF_EXTERN(largemap_6)

extern const palette_color_t largemap_6_palettes[16];
extern const uint8_t largemap_6_tiles[6944];

extern const unsigned char largemap_6_map[20592];
#define largemap_6_map_attributes largemap_6_map

#endif
