//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_gg.c -map -bpp 4 -max_palettes 2 -use_map_attributes -pack_mode gg

#ifndef METASPRITE_largemap_gg_H
#define METASPRITE_largemap_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_gg_TILE_ORIGIN 0
#define largemap_gg_TILE_W 8
#define largemap_gg_TILE_H 8
#define largemap_gg_WIDTH 1248
#define largemap_gg_HEIGHT 528
#define largemap_gg_TILES_WIDTH 156
#define largemap_gg_TILES_HEIGHT 66
#define largemap_gg_TILE_COUNT 217
#define largemap_gg_PALETTE_COUNT 1
#define largemap_gg_COLORS_PER_PALETTE 16
#define largemap_gg_TOTAL_COLORS 16
#define largemap_gg_MAP_ATTRIBUTES 0
#define largemap_gg_MAP_ATTRIBUTES_WIDTH 156
#define largemap_gg_MAP_ATTRIBUTES_HEIGHT 66
#define largemap_gg_MAP_ATTRIBUTES_PACKED_WIDTH 156
#define largemap_gg_MAP_ATTRIBUTES_PACKED_HEIGHT 66
extern const unsigned char largemap_gg_map[20592];
#define largemap_gg_map_attributes largemap_gg_map

BANKREF_EXTERN(largemap_gg)

extern const palette_color_t largemap_gg_palettes[16];
extern const uint8_t largemap_gg_tiles[6944];

#endif
