//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_sms.c -map -bpp 4 -max_palettes 2 -use_map_attributes -pack_mode sms

#ifndef METASPRITE_largemap_sms_H
#define METASPRITE_largemap_sms_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_sms_TILE_ORIGIN 0
#define largemap_sms_TILE_W 8
#define largemap_sms_TILE_H 8
#define largemap_sms_WIDTH 1248
#define largemap_sms_HEIGHT 528
#define largemap_sms_TILE_COUNT 217
#define largemap_sms_PALETTE_COUNT 1
#define largemap_sms_COLORS_PER_PALETTE 16
#define largemap_sms_TOTAL_COLORS 16
#define largemap_sms_MAP_ATTRIBUTES 0
#define largemap_sms_MAP_ATTRIBUTES_WIDTH 156
#define largemap_sms_MAP_ATTRIBUTES_HEIGHT 66
#define largemap_sms_MAP_ATTRIBUTES_PACKED_WIDTH 156
#define largemap_sms_MAP_ATTRIBUTES_PACKED_HEIGHT 66
extern const unsigned char largemap_sms_map[20592];
#define largemap_sms_map_attributes largemap_sms_map

BANKREF_EXTERN(largemap_sms)

extern const palette_color_t largemap_sms_palettes[16];
extern const uint8_t largemap_sms_tiles[6944];

#endif
