//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_4.c -map -bpp 2 -max_palettes 4 -pack_mode gb -noflip

#ifndef METASPRITE_largemap_4_H
#define METASPRITE_largemap_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_4_TILE_ORIGIN 0
#define largemap_4_TILE_W 8
#define largemap_4_TILE_H 8
#define largemap_4_WIDTH 1248
#define largemap_4_HEIGHT 528
#define largemap_4_TILE_COUNT 225
#define largemap_4_PALETTE_COUNT 4
#define largemap_4_COLORS_PER_PALETTE 4
#define largemap_4_TOTAL_COLORS 16
#define largemap_4_MAP_ATTRIBUTES 0
extern const unsigned char largemap_4_map[10296];
#define largemap_4_map_attributes largemap_4_map

BANKREF_EXTERN(largemap_4)

extern const palette_color_t largemap_4_palettes[16];
extern const uint8_t largemap_4_tiles[3600];

#endif
