//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_gb.c -map -bpp 2 -max_palettes 1 -pack_mode gb -noflip

#ifndef METASPRITE_largemap_gb_H
#define METASPRITE_largemap_gb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_gb_TILE_ORIGIN 0
#define largemap_gb_TILE_W 8
#define largemap_gb_TILE_H 8
#define largemap_gb_WIDTH 1248
#define largemap_gb_HEIGHT 528
#define largemap_gb_TILE_COUNT 225
#define largemap_gb_PALETTE_COUNT 1
#define largemap_gb_COLORS_PER_PALETTE 4
#define largemap_gb_TOTAL_COLORS 4
#define largemap_gb_MAP_ATTRIBUTES 0
extern const unsigned char largemap_gb_map[10296];
#define largemap_gb_map_attributes largemap_gb_map

BANKREF_EXTERN(largemap_gb)

extern const palette_color_t largemap_gb_palettes[4];
extern const uint8_t largemap_gb_tiles[3600];

#endif
