//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_largemap_1_H
#define METASPRITE_largemap_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_1_TILE_ORIGIN 0
#define largemap_1_TILE_W 8
#define largemap_1_TILE_H 8
#define largemap_1_WIDTH 1248
#define largemap_1_HEIGHT 528
#define largemap_1_TILE_COUNT 234
#define largemap_1_PALETTE_COUNT 4
#define largemap_1_COLORS_PER_PALETTE 4
#define largemap_1_TOTAL_COLORS 16
#define largemap_1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(largemap_1)

extern const palette_color_t largemap_1_palettes[16];
extern const uint8_t largemap_1_tiles[3744];

extern const unsigned char largemap_1_map[10296];
#define largemap_1_map_attributes largemap_1_map

#endif
