//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_nes.c -map -bpp 2 -max_palettes 4 -use_nes_attributes -pack_mode nes -noflip

#ifndef METASPRITE_largemap_nes_H
#define METASPRITE_largemap_nes_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_nes_TILE_ORIGIN 0
#define largemap_nes_TILE_W 8
#define largemap_nes_TILE_H 8
#define largemap_nes_WIDTH 1248
#define largemap_nes_HEIGHT 528
#define largemap_nes_TILES_WIDTH 156
#define largemap_nes_TILES_HEIGHT 66
#define largemap_nes_TILE_COUNT 225
#define largemap_nes_PALETTE_COUNT 4
#define largemap_nes_COLORS_PER_PALETTE 4
#define largemap_nes_TOTAL_COLORS 16
#define largemap_nes_MAP_ATTRIBUTES largemap_nes_map_attributes
#define largemap_nes_MAP_ATTRIBUTES_WIDTH 156
#define largemap_nes_MAP_ATTRIBUTES_HEIGHT 96
#define largemap_nes_MAP_ATTRIBUTES_PACKED_WIDTH 39
#define largemap_nes_MAP_ATTRIBUTES_PACKED_HEIGHT 24
extern const unsigned char largemap_nes_map[10296];
extern const unsigned char largemap_nes_map_attributes[936];

BANKREF_EXTERN(largemap_nes)

extern const palette_color_t largemap_nes_palettes[16];
extern const uint8_t largemap_nes_tiles[3600];

#endif
