//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /largemap_gbc.c -map -bpp 2 -max_palettes 8 -use_map_attributes -pack_mode gb

#ifndef METASPRITE_largemap_gbc_H
#define METASPRITE_largemap_gbc_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define largemap_gbc_TILE_ORIGIN 0
#define largemap_gbc_TILE_W 8
#define largemap_gbc_TILE_H 8
#define largemap_gbc_WIDTH 1248
#define largemap_gbc_HEIGHT 528
#define largemap_gbc_TILES_WIDTH 156
#define largemap_gbc_TILES_HEIGHT 66
#define largemap_gbc_TILE_COUNT 210
#define largemap_gbc_PALETTE_COUNT 4
#define largemap_gbc_COLORS_PER_PALETTE 4
#define largemap_gbc_TOTAL_COLORS 16
#define largemap_gbc_MAP_ATTRIBUTES largemap_gbc_map_attributes
#define largemap_gbc_MAP_ATTRIBUTES_WIDTH 156
#define largemap_gbc_MAP_ATTRIBUTES_HEIGHT 66
#define largemap_gbc_MAP_ATTRIBUTES_PACKED_WIDTH 156
#define largemap_gbc_MAP_ATTRIBUTES_PACKED_HEIGHT 66
extern const unsigned char largemap_gbc_map[10296];
extern const unsigned char largemap_gbc_map_attributes[10296];

BANKREF_EXTERN(largemap_gbc)

extern const palette_color_t largemap_gbc_palettes[16];
extern const uint8_t largemap_gbc_tiles[3360];

#endif
