//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_no_pal_map_test_H
#define METASPRITE_no_pal_map_test_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define no_pal_map_test_TILE_ORIGIN 0
#define no_pal_map_test_TILE_W 8
#define no_pal_map_test_TILE_H 8
#define no_pal_map_test_WIDTH 144
#define no_pal_map_test_HEIGHT 48
#define no_pal_map_test_TILE_COUNT 9
#define no_pal_map_test_MAP_ATTRIBUTES 0
extern const unsigned char no_pal_map_test_map[108];
#define no_pal_map_test_map_attributes no_pal_map_test_map

BANKREF_EXTERN(no_pal_map_test)

extern const uint8_t no_pal_map_test_tiles[144];

#endif
