//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_no_pal_map_test_keep_pal_order_H
#define METASPRITE_no_pal_map_test_keep_pal_order_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define no_pal_map_test_keep_pal_order_TILE_ORIGIN 0
#define no_pal_map_test_keep_pal_order_TILE_W 8
#define no_pal_map_test_keep_pal_order_TILE_H 8
#define no_pal_map_test_keep_pal_order_WIDTH 144
#define no_pal_map_test_keep_pal_order_HEIGHT 48
#define no_pal_map_test_keep_pal_order_TILE_COUNT 9
#define no_pal_map_test_keep_pal_order_MAP_ATTRIBUTES 0
extern const unsigned char no_pal_map_test_keep_pal_order_map[108];
#define no_pal_map_test_keep_pal_order_map_attributes no_pal_map_test_keep_pal_order_map

BANKREF_EXTERN(no_pal_map_test_keep_pal_order)

extern const uint8_t no_pal_map_test_keep_pal_order_tiles[144];

#endif
