//AUTOGENERATED FILE FROM png2asset
// Conversion args: /nums8x8_map_0_to_39.png -o /nums_map_8.c -map -keep_duplicate_tiles -source_tileset /nums8x8_9_to_0.png -entity_tileset /nums8x8_30_to_39.png

#ifndef METASPRITE_nums_map_8_H
#define METASPRITE_nums_map_8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_8_TILE_ORIGIN 0
#define nums_map_8_TILE_W 8
#define nums_map_8_TILE_H 8
#define nums_map_8_WIDTH 80
#define nums_map_8_HEIGHT 40
#define nums_map_8_TILES_WIDTH 10
#define nums_map_8_TILES_HEIGHT 5
#define nums_map_8_TILE_COUNT 20
#define nums_map_8_PALETTE_COUNT 1
#define nums_map_8_COLORS_PER_PALETTE 4
#define nums_map_8_TOTAL_COLORS 4
#define nums_map_8_MAP_ATTRIBUTES 0
extern const unsigned char nums_map_8_map[50];
#define nums_map_8_map_attributes nums_map_8_map

BANKREF_EXTERN(nums_map_8)

extern const uint8_t nums_map_8_tiles[320];

#endif
