//AUTOGENERATED FILE FROM png2asset
// Conversion args: /nums8x8_map_0_to_39.png -o /nums_map_3.c -map -entity_tileset /nums8x8_30_to_39.png

#ifndef METASPRITE_nums_map_3_H
#define METASPRITE_nums_map_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_3_TILE_ORIGIN 0
#define nums_map_3_TILE_W 8
#define nums_map_3_TILE_H 8
#define nums_map_3_WIDTH 80
#define nums_map_3_HEIGHT 40
#define nums_map_3_TILES_WIDTH 10
#define nums_map_3_TILES_HEIGHT 5
#define nums_map_3_TILE_COUNT 30
#define nums_map_3_PALETTE_COUNT 1
#define nums_map_3_COLORS_PER_PALETTE 4
#define nums_map_3_TOTAL_COLORS 4
#define nums_map_3_MAP_ATTRIBUTES 0
extern const unsigned char nums_map_3_map[50];
#define nums_map_3_map_attributes nums_map_3_map

BANKREF_EXTERN(nums_map_3)

extern const palette_color_t nums_map_3_palettes[4];
extern const uint8_t nums_map_3_tiles[480];

#endif
