//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nums_map_4_H
#define METASPRITE_nums_map_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_4_TILE_ORIGIN 0
#define nums_map_4_TILE_W 8
#define nums_map_4_TILE_H 8
#define nums_map_4_WIDTH 80
#define nums_map_4_HEIGHT 40
#define nums_map_4_TILE_COUNT 20
#define nums_map_4_PALETTE_COUNT 1
#define nums_map_4_COLORS_PER_PALETTE 4
#define nums_map_4_TOTAL_COLORS 4
#define nums_map_4_MAP_ATTRIBUTES 0

BANKREF_EXTERN(nums_map_4)

extern const uint8_t nums_map_4_tiles[320];

extern const unsigned char nums_map_4_map[50];
#define nums_map_4_map_attributes nums_map_4_map

#endif
