//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nums_map_6_H
#define METASPRITE_nums_map_6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_6_TILE_ORIGIN 0
#define nums_map_6_TILE_W 8
#define nums_map_6_TILE_H 8
#define nums_map_6_WIDTH 80
#define nums_map_6_HEIGHT 40
#define nums_map_6_TILE_COUNT 30
#define nums_map_6_PALETTE_COUNT 1
#define nums_map_6_COLORS_PER_PALETTE 4
#define nums_map_6_TOTAL_COLORS 4
#define nums_map_6_MAP_ATTRIBUTES 0

BANKREF_EXTERN(nums_map_6)

extern const uint8_t nums_map_6_tiles[480];

extern const unsigned char nums_map_6_map[50];
#define nums_map_6_map_attributes nums_map_6_map

#endif
