//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nums_map_1_H
#define METASPRITE_nums_map_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_1_TILE_ORIGIN 0
#define nums_map_1_TILE_W 8
#define nums_map_1_TILE_H 8
#define nums_map_1_WIDTH 80
#define nums_map_1_HEIGHT 40
#define nums_map_1_TILE_COUNT 40
#define nums_map_1_PALETTE_COUNT 1
#define nums_map_1_COLORS_PER_PALETTE 4
#define nums_map_1_TOTAL_COLORS 4
#define nums_map_1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(nums_map_1)

extern const palette_color_t nums_map_1_palettes[4];
extern const uint8_t nums_map_1_tiles[640];

extern const unsigned char nums_map_1_map[50];
#define nums_map_1_map_attributes nums_map_1_map

#endif
