//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nums_map_7_H
#define METASPRITE_nums_map_7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nums_map_7_TILE_ORIGIN 0
#define nums_map_7_TILE_W 8
#define nums_map_7_TILE_H 8
#define nums_map_7_WIDTH 80
#define nums_map_7_HEIGHT 40
#define nums_map_7_TILE_COUNT 40
#define nums_map_7_PALETTE_COUNT 1
#define nums_map_7_COLORS_PER_PALETTE 4
#define nums_map_7_TOTAL_COLORS 4
#define nums_map_7_MAP_ATTRIBUTES 0

BANKREF_EXTERN(nums_map_7)

extern const palette_color_t nums_map_7_palettes[4];
extern const uint8_t nums_map_7_tiles[640];

extern const unsigned char nums_map_7_map[50];
#define nums_map_7_map_attributes nums_map_7_map

#endif
