//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_remote_down_H
#define METASPRITE_remote_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define remote_down_TILE_ORIGIN 0
#define remote_down_TILE_W 8
#define remote_down_TILE_H 8
#define remote_down_WIDTH 160
#define remote_down_HEIGHT 144
#define remote_down_TILE_COUNT 33
#define remote_down_PALETTE_COUNT 1
#define remote_down_COLORS_PER_PALETTE 4
#define remote_down_TOTAL_COLORS 4
#define remote_down_MAP_ATTRIBUTES 0

BANKREF_EXTERN(remote_down)

extern const uint8_t remote_down_tiles[528];

extern const unsigned char remote_down_map[360];
#define remote_down_map_attributes remote_down_map

#endif
