//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_remote_H
#define METASPRITE_remote_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define remote_TILE_ORIGIN 0
#define remote_TILE_W 8
#define remote_TILE_H 8
#define remote_WIDTH 160
#define remote_HEIGHT 144
#define remote_TILE_COUNT 141
#define remote_PALETTE_COUNT 1
#define remote_COLORS_PER_PALETTE 4
#define remote_TOTAL_COLORS 4
#define remote_MAP_ATTRIBUTES 0

BANKREF_EXTERN(remote)

extern const palette_color_t remote_palettes[4];
extern const uint8_t remote_tiles[2256];

extern const unsigned char remote_map[360];
#define remote_map_attributes remote_map

#endif
