//AUTOGENERATED FILE FROM png2asset
// Conversion args: /sgb_border_multi_pal.png -c /sgb_border_multi_pal.c -map -bpp 4 -max_palettes 4 -pack_mode sgb -use_map_attributes

#ifndef METASPRITE_sgb_border_multi_pal_H
#define METASPRITE_sgb_border_multi_pal_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sgb_border_multi_pal_TILE_ORIGIN 0
#define sgb_border_multi_pal_TILE_W 8
#define sgb_border_multi_pal_TILE_H 8
#define sgb_border_multi_pal_WIDTH 256
#define sgb_border_multi_pal_HEIGHT 224
#define sgb_border_multi_pal_TILES_WIDTH 32
#define sgb_border_multi_pal_TILES_HEIGHT 28
#define sgb_border_multi_pal_TILE_COUNT 108
#define sgb_border_multi_pal_PALETTE_COUNT 3
#define sgb_border_multi_pal_COLORS_PER_PALETTE 16
#define sgb_border_multi_pal_TOTAL_COLORS 48
#define sgb_border_multi_pal_MAP_ATTRIBUTES 0
#define sgb_border_multi_pal_MAP_ATTRIBUTES_WIDTH 32
#define sgb_border_multi_pal_MAP_ATTRIBUTES_HEIGHT 28
#define sgb_border_multi_pal_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define sgb_border_multi_pal_MAP_ATTRIBUTES_PACKED_HEIGHT 28
extern const unsigned char sgb_border_multi_pal_map[1792];
#define sgb_border_multi_pal_map_attributes sgb_border_multi_pal_map

BANKREF_EXTERN(sgb_border_multi_pal)

extern const palette_color_t sgb_border_multi_pal_palettes[48];
extern const uint8_t sgb_border_multi_pal_tiles[3456];

#endif
