//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_slon_3_H
#define METASPRITE_sprite_slon_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_slon_3_TILE_ORIGIN 0
#define sprite_slon_3_TILE_W 8
#define sprite_slon_3_TILE_H 16
#define sprite_slon_3_WIDTH 64
#define sprite_slon_3_HEIGHT 48
#define sprite_slon_3_TILE_COUNT 60
#define sprite_slon_3_PALETTE_COUNT 1
#define sprite_slon_3_COLORS_PER_PALETTE 4
#define sprite_slon_3_TOTAL_COLORS 4
#define sprite_slon_3_PIVOT_X 32
#define sprite_slon_3_PIVOT_Y 24
#define sprite_slon_3_PIVOT_W 64
#define sprite_slon_3_PIVOT_H 48

BANKREF_EXTERN(sprite_slon_3)

extern const palette_color_t sprite_slon_3_palettes[4];

extern const metasprite_t* const sprite_slon_3_metasprites[5];

#endif
