//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_slon_4_H
#define METASPRITE_sprite_slon_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_slon_4_TILE_ORIGIN 0
#define sprite_slon_4_TILE_W 8
#define sprite_slon_4_TILE_H 16
#define sprite_slon_4_WIDTH 64
#define sprite_slon_4_HEIGHT 48
#define sprite_slon_4_TILE_COUNT 60
#define sprite_slon_4_PALETTE_COUNT 1
#define sprite_slon_4_COLORS_PER_PALETTE 4
#define sprite_slon_4_TOTAL_COLORS 4

BANKREF_EXTERN(sprite_slon_4)

extern const palette_color_t sprite_slon_4_palettes[4];
extern const uint8_t sprite_slon_4_tiles[960];


#endif
