//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(sprite_slon_3)

const palette_color_t sprite_slon_3_palettes[4] = {
	RGB8(255,255,255), RGB8(224,248,207), RGB8(134,192,108), RGB8(  7, 24, 33)
	
};
const metasprite_t sprite_slon_3_metasprite0[] = {
	METASPR_ITEM(-24, -24, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 4, S_PAL(0)),
	METASPR_ITEM(0, 8, 6, S_PAL(0)),
	METASPR_ITEM(0, 8, 8, S_PAL(0)),
	METASPR_ITEM(0, 8, 10, S_PAL(0)),
	METASPR_ITEM(16, -40, 12, S_PAL(0)),
	METASPR_ITEM(0, 8, 14, S_PAL(0)),
	METASPR_ITEM(0, 8, 16, S_PAL(0)),
	METASPR_ITEM(0, 8, 18, S_PAL(0)),
	METASPR_ITEM(0, 8, 20, S_PAL(0)),
	METASPR_ITEM(0, 8, 22, S_PAL(0)),
	METASPR_ITEM(0, 8, 24, S_PAL(0)),
	METASPR_ITEM(16, -48, 26, S_PAL(0)),
	METASPR_ITEM(0, 16, 28, S_PAL(0)),
	METASPR_ITEM(0, 8, 30, S_PAL(0)),
	METASPR_ITEM(0, 8, 32, S_PAL(0)),
	METASPR_ITEM(0, 8, 34, S_PAL(0)),
	METASPR_ITEM(0, 8, 36, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t sprite_slon_3_metasprite1[] = {
	METASPR_ITEM(-24, -24, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 4, S_PAL(0)),
	METASPR_ITEM(0, 8, 6, S_PAL(0)),
	METASPR_ITEM(0, 8, 8, S_PAL(0)),
	METASPR_ITEM(0, 8, 10, S_PAL(0)),
	METASPR_ITEM(16, -40, 12, S_PAL(0)),
	METASPR_ITEM(0, 8, 14, S_PAL(0)),
	METASPR_ITEM(0, 8, 16, S_PAL(0)),
	METASPR_ITEM(0, 8, 18, S_PAL(0)),
	METASPR_ITEM(0, 8, 20, S_PAL(0)),
	METASPR_ITEM(0, 8, 22, S_PAL(0)),
	METASPR_ITEM(0, 8, 38, S_PAL(0)),
	METASPR_ITEM(16, -56, 40, S_PAL(0)),
	METASPR_ITEM(0, 8, 42, S_PAL(0)),
	METASPR_ITEM(0, 16, 28, S_PAL(0)),
	METASPR_ITEM(0, 8, 30, S_PAL(0)),
	METASPR_ITEM(0, 8, 32, S_PAL(0)),
	METASPR_ITEM(0, 8, 34, S_PAL(0)),
	METASPR_ITEM(0, 8, 44, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t sprite_slon_3_metasprite2[] = {
	METASPR_ITEM(-24, -24, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 4, S_PAL(0)),
	METASPR_ITEM(0, 8, 6, S_PAL(0)),
	METASPR_ITEM(0, 8, 8, S_PAL(0)),
	METASPR_ITEM(0, 8, 10, S_PAL(0)),
	METASPR_ITEM(16, -40, 12, S_PAL(0)),
	METASPR_ITEM(0, 8, 14, S_PAL(0)),
	METASPR_ITEM(0, 8, 16, S_PAL(0)),
	METASPR_ITEM(0, 8, 18, S_PAL(0)),
	METASPR_ITEM(0, 8, 20, S_PAL(0)),
	METASPR_ITEM(0, 8, 22, S_PAL(0)),
	METASPR_ITEM(0, 8, 46, S_PAL(0)),
	METASPR_ITEM(16, -56, 48, S_PAL(0)),
	METASPR_ITEM(0, 8, 50, S_PAL(0)),
	METASPR_ITEM(0, 16, 28, S_PAL(0)),
	METASPR_ITEM(0, 8, 30, S_PAL(0)),
	METASPR_ITEM(0, 8, 32, S_PAL(0)),
	METASPR_ITEM(0, 8, 34, S_PAL(0)),
	METASPR_ITEM(0, 8, 52, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t sprite_slon_3_metasprite3[] = {
	METASPR_ITEM(-24, -24, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 4, S_PAL(0)),
	METASPR_ITEM(0, 8, 6, S_PAL(0)),
	METASPR_ITEM(0, 8, 8, S_PAL(0)),
	METASPR_ITEM(0, 8, 10, S_PAL(0)),
	METASPR_ITEM(16, -40, 12, S_PAL(0)),
	METASPR_ITEM(0, 8, 14, S_PAL(0)),
	METASPR_ITEM(0, 8, 16, S_PAL(0)),
	METASPR_ITEM(0, 8, 18, S_PAL(0)),
	METASPR_ITEM(0, 8, 20, S_PAL(0)),
	METASPR_ITEM(0, 8, 22, S_PAL(0)),
	METASPR_ITEM(0, 8, 38, S_PAL(0)),
	METASPR_ITEM(16, -56, 54, S_PAL(0)),
	METASPR_ITEM(0, 8, 56, S_PAL(0)),
	METASPR_ITEM(0, 16, 28, S_PAL(0)),
	METASPR_ITEM(0, 8, 30, S_PAL(0)),
	METASPR_ITEM(0, 8, 32, S_PAL(0)),
	METASPR_ITEM(0, 8, 34, S_PAL(0)),
	METASPR_ITEM(0, 8, 44, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t sprite_slon_3_metasprite4[] = {
	METASPR_ITEM(-24, -24, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 4, S_PAL(0)),
	METASPR_ITEM(0, 8, 6, S_PAL(0)),
	METASPR_ITEM(0, 8, 8, S_PAL(0)),
	METASPR_ITEM(0, 8, 10, S_PAL(0)),
	METASPR_ITEM(16, -40, 12, S_PAL(0)),
	METASPR_ITEM(0, 8, 14, S_PAL(0)),
	METASPR_ITEM(0, 8, 16, S_PAL(0)),
	METASPR_ITEM(0, 8, 18, S_PAL(0)),
	METASPR_ITEM(0, 8, 20, S_PAL(0)),
	METASPR_ITEM(0, 8, 22, S_PAL(0)),
	METASPR_ITEM(0, 8, 24, S_PAL(0)),
	METASPR_ITEM(16, -56, 58, S_PAL(0)),
	METASPR_ITEM(0, 8, 56, S_PAL(0)),
	METASPR_ITEM(0, 16, 28, S_PAL(0)),
	METASPR_ITEM(0, 8, 30, S_PAL(0)),
	METASPR_ITEM(0, 8, 32, S_PAL(0)),
	METASPR_ITEM(0, 8, 34, S_PAL(0)),
	METASPR_ITEM(0, 8, 36, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const sprite_slon_3_metasprites[5] = {
	sprite_slon_3_metasprite0, sprite_slon_3_metasprite1, sprite_slon_3_metasprite2, sprite_slon_3_metasprite3, sprite_slon_3_metasprite4
};
