//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_zgb_sprite_1_H
#define METASPRITE_zgb_sprite_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo zgb_sprite_1;

#endif
