//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_zgb_sushi_tiles_H
#define METASPRITE_zgb_sushi_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_sushi_tiles_tiles_info;
extern const struct MapInfo zgb_sushi_tiles;

#endif
