//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_zgb_sgb_border_1_H
#define METASPRITE_zgb_sgb_border_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_sgb_border_1_tiles_info;
extern const struct MapInfo zgb_sgb_border_1;

#endif
