//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_zgb_nums_map_4_H
#define METASPRITE_zgb_nums_map_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_nums_map_4_tiles_info;
extern const struct MapInfo zgb_nums_map_4;

#endif
