//AUTOGENERATED FILE FROM png2asset
// Conversion args: /sushi_tiles.png -c /zgb_sushi_tiles_lit.c -b 255 -area LIT -map -noflip -pack_mode sms -bpp 4 -keep_palette_order -use_structs -keep_palette_order -keep_duplicate_tiles -tiles_only

#ifndef METASPRITE_zgb_sushi_tiles_lit_H
#define METASPRITE_zgb_sushi_tiles_lit_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_sushi_tiles_lit;

#endif
